name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

          user: yashvskothari

          base: header, activity, community, repositories, metadata

          plugin_languages: yes
          plugin_habits: yes
          plugin_stars: yes
          plugin_achievements: yes
          plugin_calendar: yes
